SELECT
  TO_CHAR( TO_DATE( '&&beg_date', 'DD-MON-YYYY' ),
           'YYYY-MM-DD' ) || ',' ||
  TO_CHAR( TO_DATE( '&&end_date', 'DD-MON-YYYY' ),
           'YYYY-MM-DD' ) || ',' ||
  FABINVH_VEND_PIDM || ',}' ||
  FRVCFDA_CFDA_CODE || '},}' ||
  FRBGRNT_SPONSOR_ID || '},}' ||
  FTVFUND_FTYP_CODE || '},}' ||
  FRBGRNT_TITLE || '},}' ||
  FRBGRNT_CODE || '},}' ||
  SPRADDR_STREET_LINE1 || '},}' ||
  SPRADDR_STREET_LINE2 || '},}' ||
  SPRADDR_CITY || '},}' ||
  SPRADDR_STAT_CODE || '},}' ||
  SPRADDR_NATN_CODE || '},}' ||
  SPRADDR_ZIP || '},' ||
  VendorPaymentAmount
FROM (
  SELECT
    FABINVH_VEND_PIDM,     -- for us
    FRVCFDA_CFDA_CODE,     -- UniqueAwardNumber
    FRBGRNT_SPONSOR_ID,    -- UniqueAwardNumber
    FTVFUND_FTYP_CODE,     -- UniqueAwardNumber
    FRBGRNT_TITLE,         -- UniqueAwardNumber
    FRBGRNT_CODE,          -- RecipientAccountNumber
    SPRADDR_STREET_LINE1,  -- for us
    SPRADDR_STREET_LINE2,  -- for us
    SPRADDR_CITY,          -- for us
    SPRADDR_STAT_CODE,     -- VendorDunsNumber
    SPRADDR_NATN_CODE,     -- VendorDunsNumber
    SPRADDR_ZIP,           -- VendorDunsNumber
    SUM(FGBTRND_TRANS_AMT) VendorPaymentAmount
  FROM
    FGBTRND
    JOIN FTVFUND
      ON FTVFUND_COAS_CODE = FGBTRND_COAS_CODE
      AND FTVFUND_FUND_CODE = FGBTRND_FUND_CODE
    JOIN FRBGRNT ON FRBGRNT_CODE = FTVFUND_GRNT_CODE
    LEFT OUTER JOIN FRVCFDA
      ON FRVCFDA_INTERNAL_ID_NO = FRBGRNT_CFDA_INTERNAL_ID_NO
    JOIN FABINVH ON FABINVH_CODE = FGBTRND_DOC_CODE
    JOIN SPRADDR
      ON SPRADDR_PIDM = FABINVH_VEND_PIDM
      AND SPRADDR_ATYP_CODE = FABINVH_ATYP_CODE
      AND SPRADDR_SEQNO = FABINVH_ATYP_SEQ_NUM
  WHERE
    FRBGRNT_COAS_CODE = '&&coas'
    AND FTVFUND_FTYP_CODE IN ('4A', '4C', '4E', '4G', '4Y')     
    AND FTVFUND_DATA_ENTRY_IND = 'Y'
    AND FTVFUND_NCHG_DATE = '31-DEC-2099'
    AND SUBSTR(FGBTRND_ACCT_CODE, 1, 3) <> '156'
    AND FGBTRND_PROC_CODE IN ('O030', 'O033')
    AND FGBTRND_LEDGER_IND = 'O'
    AND FGBTRND_FSYR_CODE = '&&fsyr'
    AND FGBTRND_POSTING_PERIOD IN ('&&period1', '&&period2', '&&period3')
    AND FGBTRND_DOC_CODE IN (
      SELECT FGBTRNH_DOC_CODE
      FROM FGBTRNH
      WHERE
        FGBTRNH_VENDOR_PIDM IS NOT NULL
        AND FGBTRNH_VENDOR_PIDM NOT IN (
          SELECT FTVVENT_PIDM
          FROM FTVVENT
          WHERE FTVVENT_VTYP_CODE = 'VE'))
    AND FABINVH_VEND_PIDM NOT IN (
      SELECT FTVVENT_PIDM
      FROM FTVVENT
      WHERE FTVVENT_VTYP_CODE = 'VE')
    AND ( SPRADDR_FROM_DATE IS NULL
      OR SPRADDR_FROM_DATE < FABINVH_PMT_DUE_DATE )
    AND ( SPRADDR_TO_DATE IS NULL
      OR SPRADDR_TO_DATE > FABINVH_PMT_DUE_DATE )
  GROUP BY
    FABINVH_VEND_PIDM,
    FRVCFDA_CFDA_CODE,
    FRBGRNT_SPONSOR_ID,
    FTVFUND_FTYP_CODE,
    FRBGRNT_TITLE,
    FRBGRNT_CODE,
    SPRADDR_STREET_LINE1,
    SPRADDR_STREET_LINE2,
    SPRADDR_CITY,
    SPRADDR_STAT_CODE,
    SPRADDR_NATN_CODE,
    SPRADDR_ZIP)
WHERE VendorPaymentAmount > &&lowerlimit
;
