-- DEFINE beg_date = '2014-01-01';
-- DEFINE end_date = '2014-01-01';
-- DEFINE fsyr = '14';
-- DEFINE period1 = '07';
-- DEFINE period2 = '08';
-- DEFINE period3 = '09';
-- DEFINE coas = '1';
-- DEFINE lowerlimit=24999;

-- SELECT
--   CASE
--     WHEN SUBSTR(FRVCFDA_CFDA_CODE, 4, 3) = '000'
--       THEN '00.070 Federal - Other'
--     WHEN SUBSTR(FRVCFDA_CFDA_CODE, 1, 2) = '99'
--       THEN '00.070 Federal - Other'
--     WHEN FRVCFDA_CFDA_CODE = '93.848'
--       THEN '93.847 ' -- || NVL(FRBGRNT_SPONSOR_ID, 0)
--     ELSE FRVCFDA_CFDA_CODE -- || ' ' || NVL(FRBGRNT_SPONSOR_ID, 0)
--   END
-- FROM FRBGRNT
-- WHERE ROWNUM <= 5;

-- -- This version takes 39′ to run start to finish.
-- SELECT *
-- FROM
--   FGBTRND
-- WHERE
--   ROWNUM <= 5;

-- SELECT *
-- FROM
--   FGBTRND
--   JOIN FTVFUND ON FGBTRND_COAS_CODE = FTVFUND_COAS_CODE
--     AND FGBTRND_FUND_CODE = FTVFUND_FUND_CODE
-- WHERE
--   ROWNUM <= 5;

-- SELECT *
-- FROM
--   FGBTRND
--   JOIN FTVFUND ON FGBTRND_COAS_CODE = FTVFUND_COAS_CODE
--     AND FGBTRND_FUND_CODE = FTVFUND_FUND_CODE
--   JOIN FRBGRNT ON FTVFUND_GRNT_CODE = FRBGRNT_CODE
-- WHERE
--   ROWNUM <= 5;

-- SELECT *
-- FROM
--   FGBTRND
--   JOIN FTVFUND ON FGBTRND_COAS_CODE = FTVFUND_COAS_CODE
--     AND FGBTRND_FUND_CODE = FTVFUND_FUND_CODE
--   JOIN FRBGRNT ON FTVFUND_GRNT_CODE = FRBGRNT_CODE
--   JOIN FABINVH ON FGBTRND_DOC_CODE = FABINVH_CODE
-- WHERE
--   ROWNUM <= 5;

-- SELECT *
-- FROM
--   FGBTRND
--   JOIN FTVFUND ON FGBTRND_COAS_CODE = FTVFUND_COAS_CODE
--     AND FGBTRND_FUND_CODE = FTVFUND_FUND_CODE
--   JOIN FRBGRNT ON FTVFUND_GRNT_CODE = FRBGRNT_CODE
--   JOIN FABINVH ON FGBTRND_DOC_CODE = FABINVH_CODE
--   JOIN SPRADDR ON FABINVH_VEND_PIDM = SPRADDR_PIDM
--     AND FABINVH_ATYP_CODE = SPRADDR_ATYP_CODE
--     AND FABINVH_ATYP_SEQ_NUM = SPRADDR_SEQNO
-- WHERE
--   ROWNUM <= 5;

SELECT *
FROM
  FGBTRND
WHERE
  ROWNUM <= 5;

SELECT *
FROM
  FGBTRND, FTVFUND
WHERE
  FGBTRND_COAS_CODE = FTVFUND_COAS_CODE
  AND FGBTRND_FUND_CODE = FTVFUND_FUND_CODE
  AND ROWNUM <= 5;

SELECT *
FROM
  FGBTRND, FTVFUND, FRBGRNT
WHERE
  FGBTRND_COAS_CODE = FTVFUND_COAS_CODE
  AND FGBTRND_FUND_CODE = FTVFUND_FUND_CODE
  AND FTVFUND_GRNT_CODE = FRBGRNT_CODE
  AND ROWNUM <= 5;

SELECT *
FROM
  FGBTRND, FTVFUND, FRBGRNT, FABINVH
WHERE
  FGBTRND_COAS_CODE = FTVFUND_COAS_CODE
  AND FGBTRND_FUND_CODE = FTVFUND_FUND_CODE
  AND FTVFUND_GRNT_CODE = FRBGRNT_CODE
  AND FGBTRND_DOC_CODE = FABINVH_CODE
  AND ROWNUM <= 5;

SELECT *
FROM
  FGBTRND, FTVFUND, FRBGRNT, FABINVH, SPRADDR
WHERE
  FGBTRND_COAS_CODE = FTVFUND_COAS_CODE
  AND FGBTRND_FUND_CODE = FTVFUND_FUND_CODE
  AND FTVFUND_GRNT_CODE = FRBGRNT_CODE
  AND FGBTRND_DOC_CODE = FABINVH_CODE
  AND FABINVH_VEND_PIDM = SPRADDR_PIDM
  AND FABINVH_ATYP_CODE = SPRADDR_ATYP_CODE
  AND FABINVH_ATYP_SEQ_NUM = SPRADDR_SEQNO
  AND ROWNUM <= 5;

-- -- This is just “Docs” for the first subclause of M.N.’s full vendor
-- -- query, using joins.
-- WITH ve_pidms AS (
--   SELECT FTVVENT_PIDM pidm
--     FROM FTVVENT
--     WHERE FTVVENT_VTYP_CODE = 'VE' )
-- SELECT
--   FGBTRND_DOC_CODE,
--   FGBTRND_TRANS_AMT
-- FROM
--   FGBTRND
--   JOIN FTVFUND ON FGBTRND_COAS_CODE = FTVFUND_COAS_CODE
--     AND FGBTRND_FUND_CODE = FTVFUND_FUND_CODE
--   JOIN FRBGRNT ON FTVFUND_GRNT_CODE = FRBGRNT_CODE
--   JOIN FABINVH ON FGBTRND_DOC_CODE = FABINVH_CODE
--   JOIN SPRADDR ON FABINVH_VEND_PIDM = SPRADDR_PIDM
--     AND FABINVH_ATYP_CODE = SPRADDR_ATYP_CODE
--     AND FABINVH_ATYP_SEQ_NUM = SPRADDR_SEQNO
-- WHERE
--   FRBGRNT_COAS_CODE = '1' -- coas
--   AND FRBGRNT_SPONSOR_ID IS NOT NULL
--   AND FRBGRNT_CFDA_INTERNAL_ID_NO IS NOT NULL
--   AND FTVFUND_FTYP_CODE IN ('4A', '4C', '4E', '4G', '4Y')     
--   AND FTVFUND_DATA_ENTRY_IND = 'Y'
--   AND FTVFUND_NCHG_DATE = '31-DEC-2099' -- why?
--   AND SUBSTR(FGBTRND_ACCT_CODE, 1, 3) <> '156'
--   AND FGBTRND_PROC_CODE IN ('O030', 'O033')
--   AND FGBTRND_LEDGER_IND = 'O'
--   AND FGBTRND_FSYR_CODE = '14' -- fsyr
--   AND FGBTRND_POSTING_PERIOD IN ('07', '08', '09') -- period[123]
--   AND FGBTRND_DOC_CODE IN (
--     SELECT FGBTRNH_DOC_CODE
--     FROM FGBTRNH
--     WHERE
--       FGBTRNH_VENDOR_PIDM IS NOT NULL
--       AND FGBTRNH_VENDOR_PIDM NOT IN (SELECT pidm FROM ve_pidms))
--   AND FABINVH_VEND_PIDM NOT IN (SELECT pidm FROM ve_pidms)
--   AND ( SPRADDR_FROM_DATE IS NULL
--     OR SPRADDR_FROM_DATE < FABINVH_PMT_DUE_DATE )
--   AND ( SPRADDR_TO_DATE IS NULL
--     OR SPRADDR_TO_DATE > FABINVH_PMT_DUE_DATE )
--   AND ROWNUM <= 5;

-- -- This is just “Docs” for the first subclause of M.N.’s full vendor
-- -- query, using equivalence instead of joins.
-- WITH ve_pidms AS (
--   SELECT FTVVENT_PIDM pidm
--     FROM FTVVENT
--     WHERE FTVVENT_VTYP_CODE = 'VE' )
-- SELECT
--   FGBTRND_DOC_CODE,
--   FGBTRND_TRANS_AMT
-- FROM
--   FGBTRND,
--   FTVFUND,
--   FRBGRNT,
--   FABINVH,
--   SPRADDR
-- WHERE
--   FRBGRNT_COAS_CODE = '1' -- coas
--   AND FRBGRNT_SPONSOR_ID IS NOT NULL
--   AND FRBGRNT_CFDA_INTERNAL_ID_NO IS NOT NULL
--   AND FTVFUND_COAS_CODE = FGBTRND_COAS_CODE
--   AND FTVFUND_FUND_CODE = FGBTRND_FUND_CODE
--   AND FRBGRNT_CODE = FTVFUND_GRNT_CODE
--   AND FTVFUND_FTYP_CODE IN ('4A', '4C', '4E', '4G', '4Y')     
--   AND FTVFUND_DATA_ENTRY_IND = 'Y'
--   AND FTVFUND_NCHG_DATE = '31-DEC-2099' -- why?
--   AND SUBSTR(FGBTRND_ACCT_CODE, 1, 3) <> '156'
--   AND FGBTRND_PROC_CODE IN ('O030', 'O033')
--   AND FGBTRND_LEDGER_IND = 'O'
--   AND FGBTRND_FSYR_CODE = '14' -- fsyr
--   AND FGBTRND_POSTING_PERIOD IN ('07', '08', '09') -- period[123]
--   AND FGBTRND_DOC_CODE IN (
--     SELECT FGBTRNH_DOC_CODE
--     FROM FGBTRNH
--     WHERE
--       FGBTRNH_VENDOR_PIDM IS NOT NULL
--       AND FGBTRNH_VENDOR_PIDM NOT IN (SELECT pidm FROM ve_pidms))
--   AND FABINVH_CODE = FGBTRND_DOC_CODE
--   AND FABINVH_VEND_PIDM NOT IN (SELECT pidm FROM ve_pidms)
--   AND SPARDDR_PIDM = FABINVH_VEND_PIDM
--   AND SPRADDR_ATYP_CODE = FABINVH_ATYP_CODE
--   AND SPRADDR_SEQNO = FABINVH_ATYP_SEQ_NUM
--   AND ( SPRADDR_FROM_DATE IS NULL
--     OR SPRADDR_FROM_DATE < FABINVH_PMT_DUE_DATE )
--   AND ( SPRADDR_TO_DATE IS NULL
--     OR SPRADDR_TO_DATE > FABINVH_PMT_DUE_DATE )
--   AND ROWNUM <= 5;
