INSERT INTO countries ( iso3166, name ) VALUES ( 'AD', 'Andorra' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'AE', 'United Arab Emirates' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'AF', 'Afghanistan' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'AG', 'Antigua and Barbuda' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'AI', 'Anguilla' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'AL', 'Albania' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'AM', 'Armenia' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'AO', 'Angola' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'AQ', 'Antarctica' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'AR', 'Argentina' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'AS', 'American Samoa' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'AT', 'Austria' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'AU', 'Australia' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'AW', 'Aruba' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'AX', 'Åland Islands' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'AZ', 'Azerbaijan' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'BA', 'Bosnia and Herzegovina' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'BB', 'Barbados' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'BD', 'Bangladesh' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'BE', 'Belgium' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'BF', 'Burkina Faso' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'BG', 'Bulgaria' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'BH', 'Bahrain' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'BI', 'Burundi' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'BJ', 'Benin' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'BL', 'Saint Barthélemy' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'BM', 'Bermuda' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'BN', 'Brunei Darussalam' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'BO', 'Plurinational State of Bolivia' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'BQ', 'Bonaire, Sint Eustatius and Saba' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'BR', 'Brazil' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'BS', 'Bahamas' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'BT', 'Bhutan' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'BV', 'Bouvet Island' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'BW', 'Botswana' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'BY', 'Belarus' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'BZ', 'Belize' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'CA', 'Canada' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'CC', 'Cocos (Keeling) Islands' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'CD', 'Democratic Republic of the Congo' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'CF', 'Central African Republic' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'CG', 'Congo' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'CH', 'Switzerland' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'CI', 'Côte d’Ivoire' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'CK', 'Cook Islands' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'CL', 'Chile' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'CM', 'Cameroon' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'CN', 'China' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'CO', 'Colombia' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'CR', 'Costa Rica' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'CU', 'Cuba' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'CV', 'Cabo Verde' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'CW', 'Curaçao' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'CX', 'Christmas Island' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'CY', 'Cyprus' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'CZ', 'Czech Republic' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'DE', 'Germany' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'DJ', 'Djibouti' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'DK', 'Denmark' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'DM', 'Dominica' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'DO', 'Dominican Republic' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'DZ', 'Algeria' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'EC', 'Ecuador' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'EE', 'Estonia' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'EG', 'Egypt' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'EH', 'Western Sahara*' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'ER', 'Eritrea' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'ES', 'Spain' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'ET', 'Ethiopia' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'FI', 'Finland' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'FJ', 'Fiji' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'FK', 'Falkland Islands' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'FM', 'Federated States of Micronesia' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'FO', 'Faroe Islands' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'FR', 'France' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'GA', 'Gabon' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'GB', 'United Kingdom' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'GD', 'Grenada' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'GE', 'Georgia' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'GF', 'French Guiana' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'GG', 'Guernsey' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'GH', 'Ghana' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'GI', 'Gibraltar' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'GL', 'Greenland' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'GM', 'Gambia' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'GN', 'Guinea' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'GP', 'Guadeloupe' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'GQ', 'Equatorial Guinea' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'GR', 'Greece' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'GS', 'South Georgia and the South Sandwich Islands' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'GT', 'Guatemala' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'GU', 'Guam' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'GW', 'Guinea-Bissau' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'GY', 'Guyana' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'HK', 'Hong Kong' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'HM', 'Heard Island and McDonald Islands' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'HN', 'Honduras' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'HR', 'Croatia' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'HT', 'Haiti' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'HU', 'Hungary' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'ID', 'Indonesia' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'IE', 'Ireland' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'IL', 'Israel' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'IM', 'Isle of Man' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'IN', 'India' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'IO', 'British Indian Ocean Territory' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'IQ', 'Iraq' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'IR', 'Islamic Republic of Iran' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'IS', 'Iceland' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'IT', 'Italy' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'JE', 'Jersey' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'JM', 'Jamaica' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'JO', 'Jordan' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'JP', 'Japan' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'KE', 'Kenya' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'KG', 'Kyrgyzstan' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'KH', 'Cambodia' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'KI', 'Kiribati' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'KM', 'Comoros' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'KN', 'Saint Kitts and Nevis' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'KP', 'Democratic People’s Republic of Korea' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'KR', 'Republic of Korea' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'KW', 'Kuwait' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'KY', 'Cayman Islands' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'KZ', 'Kazakhstan' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'LA', 'Lao People’s Democratic Republic' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'LB', 'Lebanon' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'LC', 'Saint Lucia' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'LI', 'Liechtenstein' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'LK', 'Sri Lanka' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'LR', 'Liberia' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'LS', 'Lesotho' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'LT', 'Lithuania' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'LU', 'Luxembourg' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'LV', 'Latvia' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'LY', 'Libya' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'MA', 'Morocco' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'MC', 'Monaco' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'MD', 'Republic of Moldova' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'ME', 'Montenegro' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'MF', 'Saint Martin' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'MG', 'Madagascar' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'MH', 'Marshall Islands' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'MK', 'Macedonia' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'ML', 'Mali' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'MM', 'Myanmar' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'MN', 'Mongolia' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'MO', 'Macao' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'MP', 'Northern Mariana Islands' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'MQ', 'Martinique' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'MR', 'Mauritania' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'MS', 'Montserrat' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'MT', 'Malta' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'MU', 'Mauritius' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'MV', 'Maldives' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'MW', 'Malawi' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'MX', 'Mexico' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'MY', 'Malaysia' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'MZ', 'Mozambique' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'NA', 'Namibia' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'NC', 'New Caledonia' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'NE', 'Niger' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'NF', 'Norfolk Island' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'NG', 'Nigeria' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'NI', 'Nicaragua' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'NL', 'Netherlands' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'NO', 'Norway' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'NP', 'Nepal' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'NR', 'Nauru' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'NU', 'Niue' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'NZ', 'New Zealand' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'OM', 'Oman' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'PA', 'Panama' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'PE', 'Peru' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'PF', 'French Polynesia' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'PG', 'Papua New Guinea' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'PH', 'Philippines' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'PK', 'Pakistan' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'PL', 'Poland' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'PM', 'Saint Pierre and Miquelon' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'PN', 'Pitcairn' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'PR', 'Puerto Rico' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'PS', 'State of Palestine' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'PT', 'Portugal' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'PW', 'Palau' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'PY', 'Paraguay' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'QA', 'Qatar' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'RE', 'Réunion' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'RO', 'Romania' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'RS', 'Serbia' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'RU', 'Russian Federation' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'RW', 'Rwanda' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'SA', 'Saudi Arabia' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'SB', 'Solomon Islands' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'SC', 'Seychelles' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'SD', 'Sudan' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'SE', 'Sweden' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'SG', 'Singapore' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'SH', 'Saint Helena, Ascension and Tristan da Cunha' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'SI', 'Slovenia' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'SJ', 'Svalbard and Jan Mayen' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'SK', 'Slovakia' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'SL', 'Sierra Leone' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'SM', 'San Marino' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'SN', 'Senegal' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'SO', 'Somalia' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'SR', 'Suriname' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'SS', 'South Sudan' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'ST', 'Sao Tome and Principe' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'SV', 'El Salvador' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'SX', 'Sint Maarten' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'SY', 'Syrian Arab Republic' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'SZ', 'Swaziland' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'TC', 'Turks and Caicos Islands' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'TD', 'Chad' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'TF', 'French Southern Territories' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'TG', 'Togo' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'TH', 'Thailand' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'TJ', 'Tajikistan' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'TK', 'Tokelau' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'TL', 'Timor-Leste' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'TM', 'Turkmenistan' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'TN', 'Tunisia' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'TO', 'Tonga' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'TR', 'Turkey' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'TT', 'Trinidad and Tobago' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'TV', 'Tuvalu' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'TW', 'Taiwan (Republic of China)' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'TZ', 'United Republic of Tanzania' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'UA', 'Ukraine' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'UG', 'Uganda' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'UM', 'United States Minor Outlying Islands' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'US', 'United States' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'UY', 'Uruguay' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'UZ', 'Uzbekistan' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'VA', 'Holy See' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'VC', 'Saint Vincent and the Grenadines' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'VE', 'Bolivarian Republic of Venezuela' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'VG', 'British Virgin Islands' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'VI', 'U.S. Virgin Islands' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'VN', 'Viet Nam' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'VU', 'Vanuatu' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'WF', 'Wallis and Futuna' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'WS', 'Samoa' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'YE', 'Yemen' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'YT', 'Mayotte' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'ZA', 'South Africa' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'ZM', 'Zambia' );
INSERT INTO countries ( iso3166, name ) VALUES ( 'ZW', 'Zimbabwe' );
