INSERT INTO country_div_1 ( country, code, name ) VALUES ( 234, 'AA', '' );
INSERT INTO country_div_1 ( country, code, name ) VALUES ( 234, 'AK', 'Alaska' );
INSERT INTO country_div_1 ( country, code, name ) VALUES ( 234, 'AL', 'Alabama' );
INSERT INTO country_div_1 ( country, code, name ) VALUES ( 234, 'AP', '' );
INSERT INTO country_div_1 ( country, code, name ) VALUES ( 234, 'AR', 'Arkansas' );
INSERT INTO country_div_1 ( country, code, name ) VALUES ( 234, 'AZ', 'Arizona' );
INSERT INTO country_div_1 ( country, code, name ) VALUES ( 234, 'CA', 'California' );
INSERT INTO country_div_1 ( country, code, name ) VALUES ( 234, 'CO', 'Colorado' );
INSERT INTO country_div_1 ( country, code, name ) VALUES ( 234, 'CT', 'Connecticut' );
INSERT INTO country_div_1 ( country, code, name ) VALUES ( 234, 'DC', 'District of Columbia' );
INSERT INTO country_div_1 ( country, code, name ) VALUES ( 234, 'DE', 'Delaware' );
INSERT INTO country_div_1 ( country, code, name ) VALUES ( 234, 'FL', 'Florida' );
INSERT INTO country_div_1 ( country, code, name ) VALUES ( 234, 'FM', '' );
INSERT INTO country_div_1 ( country, code, name ) VALUES ( 234, 'GA', 'Georgia' );
INSERT INTO country_div_1 ( country, code, name ) VALUES ( 234, 'GU', '' );
INSERT INTO country_div_1 ( country, code, name ) VALUES ( 234, 'HI', 'Hawaii' );
INSERT INTO country_div_1 ( country, code, name ) VALUES ( 234, 'IA', 'Iowa' );
INSERT INTO country_div_1 ( country, code, name ) VALUES ( 234, 'ID', 'Idaho' );
INSERT INTO country_div_1 ( country, code, name ) VALUES ( 234, 'IL', 'Illinois' );
INSERT INTO country_div_1 ( country, code, name ) VALUES ( 234, 'IN', 'Indiana' );
INSERT INTO country_div_1 ( country, code, name ) VALUES ( 234, 'KS', 'Kansas' );
INSERT INTO country_div_1 ( country, code, name ) VALUES ( 234, 'KY', 'Kentucky' );
INSERT INTO country_div_1 ( country, code, name ) VALUES ( 234, 'LA', 'Louisiana' );
INSERT INTO country_div_1 ( country, code, name ) VALUES ( 234, 'MA', 'Massachusetts' );
INSERT INTO country_div_1 ( country, code, name ) VALUES ( 234, 'MD', 'Maryland' );
INSERT INTO country_div_1 ( country, code, name ) VALUES ( 234, 'ME', 'Maine' );
INSERT INTO country_div_1 ( country, code, name ) VALUES ( 234, 'MH', '' );
INSERT INTO country_div_1 ( country, code, name ) VALUES ( 234, 'MI', 'Michigan' );
INSERT INTO country_div_1 ( country, code, name ) VALUES ( 234, 'MN', 'Minnesota' );
INSERT INTO country_div_1 ( country, code, name ) VALUES ( 234, 'MO', 'Missouri' );
INSERT INTO country_div_1 ( country, code, name ) VALUES ( 234, 'MP', '' );
INSERT INTO country_div_1 ( country, code, name ) VALUES ( 234, 'MS', 'Mississippi' );
INSERT INTO country_div_1 ( country, code, name ) VALUES ( 234, 'MT', 'Montana' );
INSERT INTO country_div_1 ( country, code, name ) VALUES ( 234, 'NC', 'North Carolina' );
INSERT INTO country_div_1 ( country, code, name ) VALUES ( 234, 'ND', 'North Dakota' );
INSERT INTO country_div_1 ( country, code, name ) VALUES ( 234, 'NE', 'Nebraska' );
INSERT INTO country_div_1 ( country, code, name ) VALUES ( 234, 'NH', 'New Hampshire' );
INSERT INTO country_div_1 ( country, code, name ) VALUES ( 234, 'NJ', 'New Jersey' );
INSERT INTO country_div_1 ( country, code, name ) VALUES ( 234, 'NM', 'New Mexico' );
INSERT INTO country_div_1 ( country, code, name ) VALUES ( 234, 'NV', 'Nevada' );
INSERT INTO country_div_1 ( country, code, name ) VALUES ( 234, 'NY', 'New York' );
INSERT INTO country_div_1 ( country, code, name ) VALUES ( 234, 'OH', 'Ohio' );
INSERT INTO country_div_1 ( country, code, name ) VALUES ( 234, 'OK', 'Oklahoma' );
INSERT INTO country_div_1 ( country, code, name ) VALUES ( 234, 'OR', 'Oregon' );
INSERT INTO country_div_1 ( country, code, name ) VALUES ( 234, 'PA', 'Pennsylvania' );
INSERT INTO country_div_1 ( country, code, name ) VALUES ( 234, 'PW', '' );
INSERT INTO country_div_1 ( country, code, name ) VALUES ( 234, 'RI', 'Rhode Island' );
INSERT INTO country_div_1 ( country, code, name ) VALUES ( 234, 'SC', 'South Carolina' );
INSERT INTO country_div_1 ( country, code, name ) VALUES ( 234, 'SD', 'South Dakota' );
INSERT INTO country_div_1 ( country, code, name ) VALUES ( 234, 'TN', 'Tennessee' );
INSERT INTO country_div_1 ( country, code, name ) VALUES ( 234, 'TX', 'Texas' );
INSERT INTO country_div_1 ( country, code, name ) VALUES ( 234, 'UT', 'Utah' );
INSERT INTO country_div_1 ( country, code, name ) VALUES ( 234, 'VA', 'Virginia' );
INSERT INTO country_div_1 ( country, code, name ) VALUES ( 234, 'VT', 'Vermont' );
INSERT INTO country_div_1 ( country, code, name ) VALUES ( 234, 'WA', 'Washington' );
INSERT INTO country_div_1 ( country, code, name ) VALUES ( 234, 'WI', 'Wisconsin' );
INSERT INTO country_div_1 ( country, code, name ) VALUES ( 234, 'WV', 'West Virginia' );
INSERT INTO country_div_1 ( country, code, name ) VALUES ( 234, 'WY', 'Wyoming
' );