SET LINESIZE 1000;
SET PAGESIZE 0;
SET TRIMSPOOL ON;
SET HEADING OFF;
SET FEEDBACK OFF;
SPOOL spraddr_out;
SELECT SPRADDR_PIDM || ',' || SPRADDR_ZIP FROM ( SELECT DISTINCT SPRADDR_PIDM, SPRADDR_ZIP FROM SPRADDR JOIN SPRIDEN ON SPRADDR_PIDM = SPRIDEN_PIDM WHERE SPRIDEN_ENTITY_IND = 'C' AND ( SPRADDR_NATN_CODE IS NULL OR SPRADDR_NATN_CODE = 'US' ) ORDER BY SPRADDR_PIDM );
SPOOL OFF;
