SET LINESIZE 1000;
SET PAGESIZE 0;
SET TRIMSPOOL ON;
SET HEADING OFF;
SET FEEDBACK OFF;
SPOOL spriden_out;
SELECT SPRIDEN_PIDM||',}'||SPRIDEN_ID||'},}'||SPRIDEN_LAST_NAME||'},}'||SPRIDEN_FIRST_NAME||'},}'||SPRIDEN_MI||'},}'||SPRIDEN_CHANGE_IND||'},}'||SPRIDEN_ENTITY_IND||'},'||SPRIDEN_ACTIVITY_DATE||',}'||SPRIDEN_USER||'},}'||SPRIDEN_ORIGIN||'},}'||SPRIDEN_SEARCH_LAST_NAME||'},}'||SPRIDEN_SEARCH_FIRST_NAME||'},}'||SPRIDEN_SEARCH_MI||'},}'||SPRIDEN_SOUNDEX_LAST_NAME||'},}'||SPRIDEN_SOUNDEX_FIRST_NAME||'},}'||SPRIDEN_NTYP_CODE||'},}'||SPRIDEN_CREATE_USER||'},'||SPRIDEN_CREATE_DATE||',}'||SPRIDEN_DATA_ORIGIN||'},}'||SPRIDEN_CREATE_FDMN_CODE||'},}'||SPRIDEN_SURNAME_PREFIX||'},'||SPRIDEN_SURROGATE_ID||','||SPRIDEN_VERSION||',}'||SPRIDEN_USER_ID||'},}'||SPRIDEN_VPDI_CODE||'}' FROM SPRIDEN;
SPOOL OFF;
