DROP TABLE IF EXISTS spriden_raw;
CREATE TABLE IF NOT EXISTS spriden_raw (
  spriden_pidm DECIMAL(8,0) NOT NULL COMMENT 'Internal identification number of the person.',
  spriden_id VARCHAR(9) NOT NULL COMMENT 'This field defines the identification number used to access person on-line.',
  spriden_last_name VARCHAR(60) NOT NULL COMMENT 'This field defines the last name of person.',
  spriden_first_name VARCHAR(60) COMMENT 'This field identifies the first name of person.',
  spriden_mi VARCHAR(60) COMMENT 'This field identifies the middle name of person.',
  spriden_change_ind VARCHAR(1) COMMENT 'This field identifies whether type of change made to the record was an ID number change or a name change. Valid values: I - ID change, N - name change.',
  spriden_entity_ind VARCHAR(1) COMMENT 'This field identifies whether record is person or non-person record.  It does not display on the form. Valid values:  P - person, C - non-person.',
  spriden_activity_date DATE NOT NULL COMMENT 'This field defines the most current date record is created or changed.',
  spriden_user VARCHAR(30) COMMENT 'USER: The ID for the user that most recently updated the record.',
  spriden_origin VARCHAR(30) COMMENT 'ORIGIN: The name of the Banner Object that was used most recently to update the row in the spriden table.',
  spriden_search_last_name VARCHAR(60) COMMENT 'The Last Name field with all spaces and punctuation removed and all letters capitalized.',
  spriden_search_first_name VARCHAR(60) COMMENT 'The First Name field with all spaces and punctuation removed and all letters capitalized.',
  spriden_search_mi VARCHAR(60) COMMENT 'The MI (Middle Initial) field with all spaces and punctuation removed and all letters capitalized.',
  spriden_soundex_last_name VARCHAR(4) COMMENT 'The Last Name field in SOUNDEX phonetic format.',
  spriden_soundex_first_name VARCHAR(4) COMMENT 'The First Name field in SOUNDEX phonetic format.',
  spriden_ntyp_code VARCHAR(4) COMMENT 'NAME TYPE CODE: The field is used to store the code that represents the name type associated with a person’s name.',
  spriden_create_user VARCHAR(30) COMMENT 'Record Create User: This field contains Banner User ID which created new record',
  spriden_create_date DATE COMMENT 'Record Create Date: This field contains date new record created',
  spriden_data_origin VARCHAR(30) COMMENT 'DATA SOURCE: Source system that generated the data',
  spriden_create_fdmn_code VARCHAR(30) COMMENT 'PII DOMAIN: PII Domain of the user who created the spriden row.',
  spriden_surname_prefix VARCHAR(60) COMMENT 'SURNAME PREFIX: Name tag preceding the last name or surname.  (Van, Von, Mac, etc.)',
  spriden_surrogate_id DECIMAL(19,0) NOT NULL COMMENT 'SURROGATE ID: Immutable unique key',
  spriden_version DECIMAL(19,0) NOT NULL COMMENT 'VERSION: Optimistic lock token.',
  spriden_user_id VARCHAR(30) COMMENT 'USER ID: The user ID of the person who inserted or last updated this record.',
  spriden_vpdi_code VARCHAR(6) COMMENT 'VPDI CODE: Multi-entity processing code.',
  UNIQUE (spriden_surrogate_id),
  KEY (spriden_pidm),
  KEY (spriden_id),
  KEY (spriden_last_name),
  KEY (spriden_first_name),
  KEY (spriden_mi),
  KEY (spriden_search_last_name),
  KEY (spriden_search_first_name),
  KEY (spriden_search_mi),
  KEY (spriden_soundex_last_name),
  KEY (spriden_soundex_first_name)
) COMMENT = 'Duplicate of REPTPROD SATURN.SPRIDEN for analysis.';

DROP TABLE IF EXISTS spriden_norm;
CREATE TABLE IF NOT EXISTS spriden_norm (
  spriden_pidm DECIMAL(8,0) NOT NULL COMMENT 'Internal identification number of the person.',
  banner_id VARCHAR(9) COMMENT 'The Banner ID corresponds to spriden_id values starting with @.',
  uin VARCHAR(9) COMMENT 'The University ID Number of a student or employee, if known; corresponds to some spriden_id values.',
  spriden_last_name VARCHAR(60) NOT NULL COMMENT 'This field defines the last name of person.',
  spriden_first_name VARCHAR(60) COMMENT 'This field identifies the first name of person.',
  spriden_mi VARCHAR(60) COMMENT 'This field identifies the middle name of person.',
  spriden_activity_date DATE NOT NULL COMMENT 'This field defines the most current date record is created or changed.',
  spriden_search_last_name VARCHAR(60) COMMENT 'The Last Name field with all spaces and punctuation removed and all letters capitalized.',
  spriden_search_first_name VARCHAR(60) COMMENT 'The First Name field with all spaces and punctuation removed and all letters capitalized.',
  spriden_search_mi VARCHAR(60) COMMENT 'The MI (Middle Initial) field with all spaces and punctuation removed and all letters capitalized.',
  spriden_soundex_last_name VARCHAR(4) COMMENT 'The Last Name field in SOUNDEX phonetic format.',
  spriden_soundex_first_name VARCHAR(4) COMMENT 'The First Name field in SOUNDEX phonetic format.',
  spriden_create_date DATE COMMENT 'Record Create Date: This field contains date new record created',
  PRIMARY KEY (spriden_pidm),
  KEY (banner_id),
  KEY (uin),
  KEY (spriden_last_name),
  KEY (spriden_first_name),
  KEY (spriden_mi),
  KEY (spriden_search_last_name),
  KEY (spriden_search_first_name),
  KEY (spriden_search_mi),
  KEY (spriden_soundex_last_name),
  KEY (spriden_soundex_first_name)
) COMMENT = 'Semi-normalized version of SPRIDEN data.';

DROP TABLE IF EXISTS spriden_alias;
CREATE TABLE IF NOT EXISTS spriden_alias (
  id INTEGER(15) NOT NULL AUTO_INCREMENT,
  spriden_pidm DECIMAL(8,0) NOT NULL COMMENT 'Reference to the SPRIDEN entity aliased.',
  spriden_last_name VARCHAR(60) NOT NULL COMMENT 'This field defines the last name of person.',
  spriden_first_name VARCHAR(60) COMMENT 'This field identifies the first name of person.',
  spriden_mi VARCHAR(60) COMMENT 'This field identifies the middle name of person.',
  spriden_search_last_name VARCHAR(60) COMMENT 'The Last Name field with all spaces and punctuation removed and all letters capitalized.',
  spriden_search_first_name VARCHAR(60) COMMENT 'The First Name field with all spaces and punctuation removed and all letters capitalized.',
  spriden_search_mi VARCHAR(60) COMMENT 'The MI (Middle Initial) field with all spaces and punctuation removed and all letters capitalized.',
  spriden_soundex_last_name VARCHAR(4) COMMENT 'The Last Name field in SOUNDEX phonetic format.',
  spriden_soundex_first_name VARCHAR(4) COMMENT 'The First Name field in SOUNDEX phonetic format.',
  spriden_ntyp_code VARCHAR(4) COMMENT 'NAME TYPE CODE: The field is used to store the code that represents the name type associated with a person’s name.',
  PRIMARY KEY (id),
  UNIQUE (spriden_pidm, spriden_last_name, spriden_first_name, spriden_mi),
  KEY (spriden_pidm),
  KEY (spriden_last_name),
  KEY (spriden_first_name),
  KEY (spriden_mi),
  KEY (spriden_search_last_name),
  KEY (spriden_search_first_name),
  KEY (spriden_search_mi),
  KEY (spriden_soundex_last_name),
  KEY (spriden_soundex_first_name),
  FOREIGN KEY spriden_alias_pidm (spriden_pidm) REFERENCES spriden_norm (spriden_pidm)
) COMMENT = 'Alternate names for entities in SPRIDEN.';
